about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
]

addbook/urls.py
from django.urls import path
from django.contrib import admin
from addbook.views import (addbook, dynamic_lookup_view, BookList)

app_name = 'addBook'

urlpatterns = [
    path('', addbook, name='addbook'),
	path('<int:my_id>/', dynamic_lookup_view, name='books')

]

homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.homepage_view, name = "home"),
]

login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'

urlpatterns = [
	path('signin/', views.signin_view, name = "signin"),
	path('signup/', views.signup_view, name = "signup"),
	path('logout/', views.logout_view, name = "logout"),
]

onlibe2/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from addbook import views
from userprofile.views import Book_Reviews_api
from about.views import AboutList
from addbook.views import BookList


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login/', include('login.urls')),
    path('profile/',include('userprofile.urls')),
    path('search/', include('search.urls')),
    path('addbook/', include('addbook.urls')),
    path('about/', include('about.urls')),
    path('books/', views.BookList.as_view()),
    path('bookreviews/', Book_Reviews_api.as_view()),
    path('aboutapi/', AboutList.as_view()),
    path('books/', BookList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
	path('', views.search, name='search'),
	path('add_wishlist/<int:id>/', views.add_to_wishlist, name='add_wishlist')
    # dilanjutkan ...
]

userprofile/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('', views.profile, name='profile'),
    # dilanjutkan ...
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def homepage_view(request):
	return render(request, 'homepage_onlibe2.html')

homepage/templates/homepage_onlibe2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
 	
	<head>
    	
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Personal CSS Link -->
    <link rel="stylesheet" href="{% static 'css/homepage_style.css' %}">

    <!-- Bootstrap CSS Link -->
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <!-- Quicksand Font Link -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Website Title  -->
    <title>Homepage - OnLibe2</title>

  </head>

  <body>

		<!-- Bootstrap Sticky Navbar -->
  	<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top" style="box-shadow: 0 6px 20px rgba(0, 0, 0, 0.25); height: 70px; min-height: 60px;">

  		<!-- Navbar Brand/Logo -->
  		<a class="navbar-brand" href="{% url 'homepage:home' %}">
        <img src="{% static 'images/onlibe_logo.png' %}" id="logoOnLibe" style="width: 100px">
      </a>

  		<!-- Toggler/collapsibe Button -->
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
  		</button>

  		<!-- Navbar Links -->
  		<div class="collapse navbar-collapse" id="collapsibleNavbar">
  			<ul class="navbar-nav ml-auto" style="margin-right: 30px;">

  				<li class="nav-item">
            <a class="nav-link" href="{% url 'about:about' %}" style="font-family: Quicksand; font-size: 20px;"> 
              about us
            </a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'addBook:addbook' %}" style="font-family: Quicksand; font-size: 20px;"> 
              add books
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'search:search' %}" style="font-family: Quicksand; font-size: 20px;"> 
              search
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:profile' %}" style="font-family: Quicksand; font-size: 20px;"> 
              profile
            </a>
          </li>

          <li class="nav-item">
            <form class="site-form" action="{% url 'login:logout' %}" method="post">
              {% csrf_token %}
              <a class="nav-link" href="{% url 'login:logout' %}" style="font-family: Quicksand; font-size: 20px;">
                log out
              </a>
            </form>
          </li>

          {% else %}
    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'login:signin' %}" style="font-family: Quicksand; font-size: 20px;"> 
      				sign in
      			</a>
    			</li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'login:signup' %}" style="font-family: Quicksand; font-size: 20px;"> 
      				sign up
      			</a>
    			</li>
          {% endif %}

  			</ul>
  		</div>

		</nav>

    <!-- Bootstrap Row & Column Container -->
    <div class="row">

      <!-- Bootstrap Responsive Column Span-6 (Page Left-Side) -->
    	<div class="col-md-6">

        <div class="container" style="margin-top:50px; margin-bottom:50px; padding-right: 5%; padding-left: 5%">

          <div class="container my-3">

            <h1 class="border-bottom mb-4" style="font-family: Quicksand; font-weight: normal; font-size: 60px;">
              <strong>YOUR BOOK IS CALLING!</br> YOUR JOURNEY AWAITS!</strong>
            </h1>

            <h4 style="font-family: Quicksand; font-size: 30px; line-height: 30px;"> 
              Go and collect your <strong>online</strong> books right here, right now at 
              <img src="{% static 'images/onlibe-text.png' %}" style="width:auto; max-height: 30px;">
            </h4>

            <!-- Signin & Signup Button Container -->
            <div class="row">

              <!-- Signin Button -->
              <form action="{% url 'login:signin' %}" method="post">
        				{% csrf_token %}

        				<button class="btn btn-lg text-white" style="background-color:#44459F; margin:15px" type="submit">
        					view your books
        				</button>

        			</form>

        			<!-- Signup Button -->
              <form action="{% url 'login:signup' %}" method="post">
        				{% csrf_token %}

        				<button class="btn btn-lg text-white" style="background-color:#44459F; margin:15px" type="submit">
        					become a member
        				</button>

        			</form>
            
            </div>

          </div>

        </div>

      </div>

      <!-- Bootstrap Responsive Column Span-6 (Page Right-Side) -->
      <div class="col-md-6">

        <div class="container" style="padding-top: 5%; padding-right: 0%; padding-bottom: 0%">
          <img class="img-fluid float-right" src="{% static 'images/reading_man.png' %}">
        </div>
      
      </div>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>